stages:
  prepare:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
    outs:
      - data/california_housing.csv

  train:
    cmd: python src/train.py
    deps:
      - data/california_housing.csv
      - src/train.py
      - src/utils.py
      - src/predict.py
    outs:
      - models/metrics.json
      - models/best_model.json
